import React from "react";
import {
  AbsoluteFill,
  interpolate,
  useCurrentFrame,
  Easing,
} from "remotion";
import { RoutePath } from "../components/RoutePath";
import type { LatLng } from "../utils/normalizeRoute";
import {
  capitalize,
  formatDate,
  formatDistance,
  formatDuration,
  formatPace,
  formatElevation,
} from "../utils/format";

interface FinalCardSceneProps {
  brandName: string;
  sport: string;
  date: string;
  durationSeconds: number;
  distanceMeters: number;
  avgPaceSecPerKm: number | null;
  totalElevGainMeters: number | null;
  routePoints: LatLng[];
  durationFrames: number;
}

export const FinalCardScene: React.FC<FinalCardSceneProps> = ({
  brandName,
  sport,
  date,
  durationSeconds,
  distanceMeters,
  avgPaceSecPerKm,
  totalElevGainMeters,
  routePoints,
  durationFrames,
}) => {
  const frame = useCurrentFrame();

  // Fade up; do not fade out at the end so the final frame is a clean still
  const opacity = interpolate(frame, [0, 16], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const slideUp = interpolate(frame, [0, 24], [30, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });

  // Make the route appear as fully drawn, instantly (no animation here)
  const ROUTE_W = 920;
  const ROUTE_H = 520;

  const Stat = ({ label, value }: { label: string; value: string }) => (
    <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
      <div
        style={{
          fontSize: 22,
          fontWeight: 500,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "rgba(255,255,255,0.5)",
        }}
      >
        {label}
      </div>
      <div
        style={{
          fontSize: 56,
          fontWeight: 700,
          letterSpacing: "-0.02em",
          color: "#ffffff",
          fontVariantNumeric: "tabular-nums",
        }}
      >
        {value}
      </div>
    </div>
  );

  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#08090a",
        opacity,
        display: "flex",
        flexDirection: "column",
        padding: 80,
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          background:
            "radial-gradient(ellipse 70% 50% at 50% 25%, rgba(113,112,255,0.10), transparent 65%)",
          pointerEvents: "none",
        }}
      />

      <div
        style={{
          transform: `translateY(${slideUp}px)`,
          marginTop: 40,
          zIndex: 1,
        }}
      >
        <div
          style={{
            fontSize: 78,
            fontWeight: 700,
            letterSpacing: "-0.03em",
            color: "#ffffff",
            lineHeight: 1.05,
          }}
        >
          {capitalize(sport)}
        </div>
        <div
          style={{
            fontSize: 30,
            fontWeight: 400,
            color: "rgba(255,255,255,0.55)",
            marginTop: 8,
          }}
        >
          {formatDate(date)}
        </div>
      </div>

      <div
        style={{
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          marginTop: 24,
          zIndex: 1,
        }}
      >
        <RoutePath
          points={routePoints}
          width={ROUTE_W}
          height={ROUTE_H}
          padding={40}
          // Negative startFrame ⇒ already fully drawn at frame 0
          startFrame={-1000}
          drawDurationFrames={1}
          stroke="#ffffff"
          glow="rgba(113,112,255,0.55)"
          startDot="#4ade80"
          headDot="#7170ff"
        />
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          rowGap: 40,
          columnGap: 60,
          padding: "32px 0",
          borderTop: "1px solid rgba(255,255,255,0.10)",
          borderBottom: "1px solid rgba(255,255,255,0.10)",
          zIndex: 1,
        }}
      >
        <Stat label="Distance" value={formatDistance(distanceMeters)} />
        <Stat label="Time" value={formatDuration(durationSeconds)} />
        <Stat label="Pace" value={formatPace(avgPaceSecPerKm)} />
        <Stat label="Elevation" value={formatElevation(totalElevGainMeters)} />
      </div>

      <div
        style={{
          marginTop: 28,
          textAlign: "center",
          fontSize: 24,
          fontWeight: 400,
          color: "rgba(255,255,255,0.45)",
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          zIndex: 1,
        }}
      >
        Generated by {brandName}
      </div>
    </AbsoluteFill>
  );
};
